# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 804573c0d84142a804fc76523982f0e775cd57c82646094c6cc329cfda8071d06a0af3140dbb7c613982b88c53cf23208fcc572dd18e46412f205be287efa024

test:
  secret_key_base: 603a57d9d23cdd0cc955cfd0fb2df72cb8568c40c70e3cd8333243e06fe9495f2842eb5d8e1dcce97a75b86c71b4a8ff2550d225f87f38a1da0ce6c43856dba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
